apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: apis
  namespace: api
spec:
  host: api.example.com
  upstreams:
  - name: generator
    service: generator
    port: 80
  routes:
  - path: =/api/v1
    pass: generator
  - path: /api/v1
    route: api/api
  - path: /api/v2
    route: apiv2/api
