apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: apiv2
  namespace: apiv2
spec:
  host: api.example.com
  upstreams:
  - name: colors2
    service: colors-v2
    port: 80
  - name: locations2
    service: locations-v2
    port: 80
  - name: animals2
    service: animals-v2
    port: 80
  - name: adjectives2
    service: adjectives-v2
    port: 80
  subroutes:
  - path: /api/v2/locations
    action:
      proxy:
        rewritePath: /locations
        upstream: locations2
  - path: /api/v2/colors
    action:
      proxy:
        rewritePath: /colors
        upstream: colors2
  - path: /api/v2/animals
    action:
      proxy:
        rewritePath: /animals
        upstream: animals2
  - path: /api/v2/adjectives
    action:
      proxy:
        rewritePath: /animals
        upstream: animals2

