apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: apis
  namespace: apiv2
spec:
  host: api.example.com
  upstreams:
  - name: generator
    service: generator
    port: 80
  - name: locations
    service: locations
    port: 80
  - name: animals
    service: animals
    port: 80
  - name: adjectives
    service: adjectives
    port: 80
  - name: colors
    service: colors
    port: 80
  routes:
  - path: =/api/v1
    action:
      pass: generator
  - path: /api/locations
    route: apiv2/locations
  - path: /api/v2/animals
    action:
      proxy: 
        upstream: animals
        rewritePath: /animals
  - path: /api/v2/colors
    action:
      proxy: 
        upstream: colors
        rewritePath: /colors
  - path: /api/v2/adjectives
    action:
      proxy: 
        upstream: adjectives
        rewritePath: /adjectives
