apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: apis
  namespace: apiv2
spec:
  host: api.example.com
  upstreams:
  - name: locations
    service: locations
    port: 80
  - name: animals
    service: animals
    port: 80
  - name: adjectives
    service: adjectives
    port: 80
  - name: colors
    service: colors
    port: 80
  routes:
  - path: /api/locations/v2
    action:
      pass: locations
  - path: /api/animals/v2
    action:
      pass: animals
  - path: /api/colors/v2
    action:
      pass: colors
  - path: /api/adjectives/v2
    action:
      pass: adjectives
