---
apiVersion: v1
kind: Service
metadata:
  name: animals
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: animals
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animals
  template:
    metadata:
      labels:
        app: animals
    spec:
      containers:
      - name: animals
        image: spoyer/animals
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
