---
apiVersion: v1
kind: Service
metadata:
  name: animalsv2
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: animalsv2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: animalsv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animalsv2
  template:
    metadata:
      labels:
        app: animalsv2
    spec:
      containers:
      - name: animalsv2
        image: spoyer/animals
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
