apiVersion: v1
kind: Service
metadata:
  labels:
    app: oas-spec
  name: colors-spec-svc
  namespace: spec
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: oas-spec
