apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-policy
  namespace: api
spec:
  waf:
   enable: true
   apPolicy: "api/dataguard-alarm"
   securityLog:
      enable: true
      apLogConf: "api/logconf"
      logDest: "syslog:server=syslog-svc.api:514"