apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: grpc-vs
  namespace: api
spec:
  host: grpc.example.com
  tls:
    secret: grpc-secret
  upstreams:
  - name: echo
    service: echo-grpc
    port: 8081
    type: grpc
  - name: reverse
    service: reverse-grpc
    port: 8082
    type: grpc
  routes:
  - path: /api.Echo/Echo
    action:
      pass: echo
  - path: /api.Reverse/Reverse
    action:
      pass: reverse
    
